name: "Local public"
author: "Test"
steps:
  - id: step-a
    name: "Git"
    action: install
    packages: git
  - id: step-b
    name: "Local"
    action: run
    cmd: |
      echo 'Found local recipe'
    requires:
      - step-a
